# STATISTICS

Statistics helps us to collect, organize, analyze and interpret data to find patterns.

Types of Statistics 

 1. Descriptive Statistics
 2. Inferential Statistics

Descriptive Statistics simplify and organise big datas which helps us to understand easily

Inferential Statistics uses small datas to conclude a large group

# Types of Analytics:

Predictive Analysis: It tells the future outcomes based on historical data.
                     It helps us to understand what will happen next.

Prescriptive Analysis: It recommends us the specific action to achieve the outcomes based on predictions

Population: It refers to the entire group of individuals or items that you want to draw conclusion.
sample: it is a subset of that population selected for analysis .
The sample size is always less than the total size of the population. 

Types of DATA

# Numerical (Quantitative Analysis)

  1.Discrete (finite options)- Eg: Students in a class, Shoe size
  
  2.Continous(Infinite Options)- Eg: Age , Weight , Blood Pressure

# Categorical (Qualitative Analysis)

  1.Nominal (Data has no hierarchy) - Eg: Eye color , Blood Types 
  
  2.Ordinal (Data with hierarchy or order) - Eg: Grades , Rating Scale


Descriptive Statistics: 
1.Numerical Measures :

                     a.) Measure of central Tendency
                    
                    b.)Measure of Symmetry/ shapes 
                    
                    c.)Measure of dispersion/ Spreads



a.) Measure of central Tendency : Summarize and describe the central or average value around the data .Mean , Median Mode

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Mean : Average value , which is most commonly used to measure the Central tendency

In [3]:
data = [45, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [4]:
mean=sum(data)/len(data)

In [5]:
mean

72.0

Median : Median of a smaple is the middle value when the data are arranged in ascending or descending order.

In [31]:
median=pd.Series(data).median()
median

np.float64(72.5)

Mode : The Mode is the value that occurs most frequently.Represents the highest peak of distribution

2.Measure of spread /Depression

1.Standard Deviation 
  measure of how on average the observations are from the mean.Sum of Square Deviations.It is also square root of variance.    

In [51]:
std=pd.Series(data).std()
std

np.float64(16.020819787597222)

2.Variance is a total value divided by (n-1).

In [32]:
import numpy as np

In [33]:
data = [45, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [34]:
#sample variance ddof = delta degree of freedom
sv=np.var(data,ddof=2)

In [35]:
sv

np.float64(288.75)

In [36]:
#entire data variance
sv1=np.var(data)

In [37]:
sv1

np.float64(231.0)

Range : Difference between the largest and smallest observations in the data set.

In [38]:
r=max(data)-min(data)

In [39]:
r

50

In [40]:
df=pd.DataFrame(data)

In [41]:
df

0
0  45
1  55
2  60
3  65
4  70
5  75
6  80
7  85
8  90
9  95

Percentile: Tells you the percentage of data values below a specific point.

In [42]:
q1=np.percentile(data,25)

In [43]:
q1

np.float64(61.25)

In [44]:
q2=np.percentile(data,50)

In [45]:
q2

np.float64(72.5)

IQR Inter Quartile Range
The interquartile range (IQR) is another measure of spread which is like the range but which is not affected by the data extremes.
Used to remove Outliers 

In [46]:
iqr=q2-q1

In [47]:
iqr

np.float64(11.25)

# 3.Measure of Symmetry:

  a.)Skewness : Skewed to the left , Skewed to the Right
      

In [55]:
df.skew()

0   -0.200632
dtype: float64

skewness between -0.5 to +0.5 =Fairly Symmetrical 

skewness is -1 and -0.5 or +1 and +0.5 =Moderately skewed

skewness is less than -1 or greater than 1  = Highly skewed

b.)Kurtosis: 

In [58]:
df.kurt()

0   -0.841837
dtype: float64

Meso kurtosis: values between 0 and 3

Lepto kurtosis: Less than 3 by value 

platykurtosis: Values are greater than 3

# Inferential Statistics:

In [62]:
pop=np.arange(1,100)
pop

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [64]:
sample=np.random.choice(pop,size=10,replace=False)
sample

array([95, 20, 63, 86, 46, 53,  1, 84, 77, 17])

In [65]:
print("sample.mean()",sample.mean())

sample.mean() 54.2


Simple sampling : Equal chance for everyone.

Systematic Sampling : It is quick and easy to use but the list must not be biased . Main feature of it is Every k-th item is selected.

Stratified Sampling : Sample from each subgroup , Population has important categories.

Cluster :  Select whole groups , Natural groups exist, cost-saving .

# hypothesis testing

T - test 

In [67]:
from scipy import stats

In [68]:
np.random.seed(42)

In [69]:
sample = np.random.normal(loc=503, scale=5, size=30)
sample

array([505.48357077, 502.30867849, 506.23844269, 510.61514928,
       501.82923313, 501.82931522, 510.89606408, 506.83717365,
       500.65262807, 505.71280022, 500.68291154, 500.67135123,
       504.20981136, 493.43359878, 494.37541084, 500.18856235,
       497.9358444 , 504.57123666, 498.45987962, 495.93848149,
       510.32824384, 501.8711185 , 503.33764102, 495.87625907,
       500.27808638, 503.55461295, 497.24503211, 504.87849009,
       499.99680655, 501.54153125])

In [70]:
t_statistic, p_value = stats.ttest_1samp(sample, popmean=500)

Printing the testing T- statistic value

In [71]:
print("T-statistic:", t_statistic)

T-statistic: 2.5064402725654054


Finding the P-value

In [72]:
print("P-value:", p_value)

P-value: 0.018054505756327662


In [74]:
a=.05

In [75]:
#decision 

if p_value < a:
    print("work from home is good")
else:
    print("work from home not good.")
    

work from home is good


In [77]:
# Simulate a sample of 40 student scores

np.random.seed(32)
sample = np.random.normal(loc=72, scale=5, size=40)

In [79]:
sample 

array([70.25552775, 76.91851717, 74.90461415, 72.3514222 , 75.88766338,
       74.90979373, 79.35895263, 80.31590504, 70.69411439, 68.55661594,
       68.52538369, 81.7021173 , 81.02707595, 74.28156926, 69.1259398 ,
       72.57090252, 79.56790385, 73.7556592 , 71.55533393, 76.58477114,
       74.52822563, 67.92364445, 73.94575476, 69.87518765, 72.19811576,
       69.36018039, 69.4484816 , 67.55857425, 77.43812367, 75.36696132,
       66.66341482, 78.09024992, 88.81856274, 67.83873299, 70.2982581 ,
       62.70714228, 72.00411533, 73.75787241, 79.60754424, 68.59762931])

In [80]:
pop_mean=70
pop_std=5

In [ ]:
Here the mean and the standard  deviation value is being found.

# Probability

Experiment: Doing something and looking at the result; e.g. rolling a dice

Outcome: A single possible outcome of an experiment

Event: A set of one or more outcome;e.g. for a dice {1}, {2}, …, {6]  A random variable is a variable

 It Can be either discrete (having specific values) or continuous (any value in a continuous range).

Probability distribution (probality density function) PDF-continous function

probability mass function ,PMF - discrete function 

# Uniform Distribution:
When the chances of every possible outcome is same. Ex: Rolling of Dice

# Bernoulli distribution: 
Bernoulli distribution, Ber(p), is used to model an experiment with only two possible outcomes.
The two outcomes are often encoded as 1 and 0. Ex:tossing a coin

Binomial distribution: models the number of successes when someone draws n times with replacement. Each draw or experiment is independent, with two possible outcomes.

Normal distribution, T-distribution, Chi Square Distribution and F Distribution

Mean = Median = Mode | Symmetry about the center | 50% of values less than the mean and 50% greater than the mean 68-95-99.7 Rule : 68% of values are within 1 standard deviation of the mean, 95% within 2and 99.7 within 3 SD

central limit theorem - sample should be greater than 30

In [86]:
even = {2, 4, 6}
greater_than_3 = {4, 5, 6}
sample_space = set(range(1, 7))
#Event intersections and properties
intersection = even & greater_than_3
union = even | greater_than_3

In [87]:
print(f"Even numbers: {even}")
print(f"Greater than 3: {greater_than_3}")
print(f"Intersection (A ∩ B): {intersection}")
print(f"Union (A ∪ B): {union}")

Even numbers: {2, 4, 6}
Greater than 3: {4, 5, 6}
Intersection (A ∩ B): {4, 6}
Union (A ∪ B): {2, 4, 5, 6}
